on:
  push:
    branches: ["main"]
    paths-ignore:
      - "CHANGELOG.md"
      - "CHANGELOG_PENDING.md"
      - "README.md"

jobs:
  runcode:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
          check-latest: true
      - run: |
          go build
      - run: |
          ./temp-check-go-windows-behavior.exe
